#this is modification of the file ORG-frontend-deployment.YAML where I have added environmental variables REDIS_MASTER_SERVICE_HOST and REDIS_SLAVE_SERVICE_HOST so that the 
#internal DNS service is not being used
#befoe using it in your project make sure you put the right IP addresses below. These are IP addresses of the services exposed by Redis Master and Redis Slave Service via 
#an internal load balancer

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-case2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend-case2
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          #value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: 10.132.0.8
        - name: REDIS_SLAVE_SERVICE_HOST
          value: 10.132.0.9
        ports:
        - containerPort: 80

