---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "redis-slave-service"
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  namespace: "default"
  labels:
    app: "redis"
    role: "slave"
    tier: "backend"
spec:
  ports:
  - protocol: "TCP"
    port: 6379
  selector:
    app: "redis"
    role: "slave"
    tier: "backend"
  type: "LoadBalancer"
  loadBalancerIP: ""

